# thymeleaf
spring:
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    enabled: true
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #druid
  datasource:
    url: jdbc:mysql://47.98.143.42:3306/miaosha?user=root&password=&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1qazXDR%
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filers: stat
    maxActive: 2
    initialSize: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


# mybaties
mybatis:
  type-aliases-package: zxbv.online.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    mapperLocations: classpath:mapper/*.xml


